// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Supabase configuration - must use NEXT_PUBLIC_ prefix for client-side access
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";

// Only validate at runtime in the browser (not during build or in tests)
const isBrowser = typeof window !== 'undefined';
const isProduction = process.env.NODE_ENV === 'production';

if (isBrowser && isProduction && (!SUPABASE_URL || !SUPABASE_ANON_KEY)) {
  console.error("Missing Supabase environment variables. Please check your configuration.");
}

// Use dummy values during build if not set
const url = SUPABASE_URL || "https://placeholder.supabase.co";
const key = SUPABASE_ANON_KEY || "placeholder-key";

export const supabase = createClient<Database>(url, key, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: "public",
  },
});